import { defineConfig } from 'astro/config';
import mdx from '@astrojs/mdx';
import remarkMath from 'remark-math';
import rehypeKatex from 'rehype-katex';
import remarkDirective from 'remark-directive';
import { remarkBilingualDirective } from './src/plugins/remark-bilingual.mjs';

export default defineConfig({
  site: 'https://alanhou.org',
  output: 'static',
  integrations: [mdx()],
  redirects: {
    '/installing-odoo-development-environment': '/blog/installing-odoo-development-environment',
    '/managing-odoo-server-instances': '/blog/managing-odoo-server-instances',
    '/server-deployment': '/blog/server-deployment',
    '/creating-odoo-add-on-modules': '/blog/creating-odoo-add-on-modules',
    '/application-models': '/blog/application-models',
    '/basic-server-side-development': '/blog/basic-server-side-development',
    '/odoo12-module-data': '/blog/odoo12-module-data',
    '/debugging': '/blog/debugging',
    '/advanced-server-side-development-techniques': '/blog/advanced-server-side-development-techniques',
    '/backend-views': '/blog/backend-views',
    '/access-security': '/blog/access-security',
    '/internationalization': '/blog/internationalization',
    '/automation-workflows-printouts': '/blog/automation-workflows-printouts',
    '/web-server-development': '/blog/web-server-development',
    '/cms-website-development': '/blog/cms-website-development',
    '/web-client-development': '/blog/web-client-development',
    '/in-app-purchasing-odoo': '/blog/in-app-purchasing-odoo',
    '/automated-test-cases': '/blog/automated-test-cases',
    '/managing-deploying-testing-odoo-sh': '/blog/managing-deploying-testing-odoo-sh',
    '/remote-procedure-calls-odoo': '/blog/remote-procedure-calls-odoo',
    '/performance-optimization': '/blog/performance-optimization',
    '/point-sale': '/blog/point-sale',
    '/manage-emails-odoo': '/blog/manage-emails-odoo',
    '/iot-box': '/blog/iot-box',
    '/odoo-14-installing-odoo-development-environment': '/blog/odoo-14-installing-odoo-development-environment',
    '/odoo-14-managing-odoo-server-instances': '/blog/odoo-14-managing-odoo-server-instances',
    '/odoo-14-creating-odoo-add-on-modules': '/blog/odoo-14-creating-odoo-add-on-modules',
    '/odoo-14-application-models': '/blog/odoo-14-application-models',
    '/odoo-14-basic-server-side-development': '/blog/odoo-14-basic-server-side-development',
    '/odoo-14-module-data': '/blog/odoo-14-module-data',
    '/odoo-14-debugging': '/blog/odoo-14-debugging',
    '/odoo-14-advanced-server-side-development-techniques': '/blog/odoo-14-advanced-server-side-development-techniques',
    '/odoo-14-backend-views': '/blog/odoo-14-backend-views',
    '/odoo-14-access-security': '/blog/odoo-14-access-security',
    '/odoo-14-internationalization': '/blog/odoo-14-internationalization',
    '/odoo-14-automation-workflows-printouts': '/blog/odoo-14-automation-workflows-printouts',
    '/odoo-14-web-server-development': '/blog/odoo-14-web-server-development',
    '/odoo-14-cms-website-development': '/blog/odoo-14-cms-website-development',
    '/odoo-14-web-client-development': '/blog/odoo-14-web-client-development',
    '/odoo-14-odoo-web-library-owl': '/blog/odoo-14-odoo-web-library-owl',
    '/odoo-14-in-app-purchasing-odoo': '/blog/odoo-14-in-app-purchasing-odoo',
    '/odoo-14-automated-test-cases': '/blog/odoo-14-automated-test-cases',
    '/odoo-14-remote-procedure-calls-odoo': '/blog/odoo-14-remote-procedure-calls-odoo',
    '/odoo-14-performance-optimization': '/blog/odoo-14-performance-optimization',
    '/odoo-14-manage-emails-odoo': '/blog/odoo-14-manage-emails-odoo',
    '/odoo-14-managing-deploying-testing-odoo-sh': '/blog/odoo-14-managing-deploying-testing-odoo-sh',
    '/odoo-14-point-sale': '/blog/odoo-14-point-sale',
    '/odoo-14-iot-box': '/blog/odoo-14-iot-box',
    '/developer-mode-odoo12': '/blog/developer-mode-odoo12',
    '/odoo12-development-environment': '/blog/odoo12-development-environment',
    '/odoo12-first-application': '/blog/odoo12-first-application',
    '/odoo12-extending-modules': '/blog/odoo12-extending-modules',
    '/odoo12-import-export-data': '/blog/odoo12-import-export-data',
    '/odoo12-structuring-data': '/blog/odoo12-structuring-data',
    '/odoo12-recordsets': '/blog/odoo12-recordsets',
    '/odoo12-business-logic': '/blog/odoo12-business-logic',
    '/odoo12-external-api': '/blog/odoo12-external-api',
    '/odoo12-backend-views': '/blog/odoo12-backend-views',
    '/odoo12-kanban-qweb': '/blog/odoo12-kanban-qweb',
    '/odoo12-reports-qweb': '/blog/odoo12-reports-qweb',
    '/odoo12-frontend': '/blog/odoo12-frontend',
    '/odoo12-deployment': '/blog/odoo12-deployment',
    '/python-scripting-overview': '/blog/python-scripting-overview',
    '/debugging-profiling-python-scripts': '/blog/debugging-profiling-python-scripts',
    '/unit-testing-introduction-unit-testing-framework': '/blog/unit-testing-introduction-unit-testing-framework',
    '/automating-regular-administrative-activities': '/blog/automating-regular-administrative-activities',
    '/handling-files-directories-data': '/blog/handling-files-directories-data',
    '/file-archiving-encrypting-decrypting': '/blog/file-archiving-encrypting-decrypting',
    '/text-processing-regular-expressions': '/blog/text-processing-regular-expressions',
    '/documentation-reporting': '/blog/documentation-reporting',
    '/working-files': '/blog/working-files',
    '/basic-networking-socket-programming': '/blog/basic-networking-socket-programming',
    '/handling-emails-python-scripting': '/blog/handling-emails-python-scripting',
    '/remote-monitoring-hosts-telnet-ssh': '/blog/remote-monitoring-hosts-telnet-ssh',
    '/building-graphical-user-interfaces': '/blog/building-graphical-user-interfaces',
    '/working-apache-log-files': '/blog/working-apache-log-files',
    '/soap-rest-api-communication': '/blog/soap-rest-api-communication',
    '/web-scraping-extracting-data-websites': '/blog/web-scraping-extracting-data-websites',
    '/statistics-gathering-reporting': '/blog/statistics-gathering-reporting',
    '/mysql-sqlite-database-administrations': '/blog/mysql-sqlite-database-administrations',
  },
  markdown: {
    remarkPlugins: [remarkMath, remarkDirective, remarkBilingualDirective],
    rehypePlugins: [rehypeKatex],
  },
});
